apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: hadiya
  labels:
    project: hadiya
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_root_password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql_database
          volumeMounts:
            - name:  mysql-volume
              mountPath:  /var/lib/mysql
      volumes:
        - name: mysql-volume
          hostPath:
            path: /var/data/mysql
            type: DirectoryOrCreate