apiVersion: v1
kind: Service
metadata:
  name: products-service
  namespace: hadiya
spec:
  type: NodePort
  selector:
    app: products
  ports:
  - name:  products-api-port
    port:  3000
    targetPort: 3000
    nodePort: 30000
    protocol: TCP